export const WORK_EXPEREICNE = [
  {
    company: 'Software Q',
    companySlogan: 'Digital Insurance Bridge For Partners',
    project: 'Senang',
    companyWebsite: 'https://www.softwareq.com/',
    companyLogo:
      'https://static.wixstatic.com/media/e79bab_ba2d5c2cad4e4eadaa6b8e1a01ea6b41~mv2.png/v1/fill/w_592,h_58,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/e79bab_ba2d5c2cad4e4eadaa6b8e1a01ea6b41~mv2.png',

    projectUrl: 'https://senang.io/',
    position: 'Senior Software Engineer',
    timeline: 'April 2024 - Present',
    workDescription: [
      'As a Senior Software Engineer at Senang, I specialize in Angular development.',
      'Leading the implementation of enhancements to web applications, enhancing user experiences at Senang.',
      'My expertise lies in frontend technologies, ensuring the creation of intuitive and responsive interfaces.',
      'Active engagement in daily coordination with an international team at Senang to facilitate cross-border collaboration.',
    ],
  },
  {
    company: 'Resimator',
    companySlogan: 'Platform for better tenant experience',
    project: 'Izy',
    companyWebsite: 'https://resimator.fi/en',
    companyLogo: '../../../../assets/images/resimator_logo.jpeg',
    projectUrl: 'https://izy.no/en/',
    position: 'Senior Software Engineer',
    timeline: 'Nov 2022 - Feb 2024',
    workDescription: [
      'Senior Software Engineer at Izy, specializing in Angular, .NET, and C# development.',
      'Led web application enhancements for improved user experiences at Izy.',
      'Proficient in .NET for scalable solutions and seamless feature integration.',
      'Daily international team coordination at Izy for cross-border collaboration.',
    ],
  },
  {
    company: 'Whitehat Engineering',
    companySlogan: 'Restaurant Accounting that Accelerates Growth',
    project: 'Rasi',
    projectUrl: 'https://rasiusa.com/',
    position: 'Senior Software Engineer',
    timeline: 'Sep 2022 - Jun 2023',
    workDescription: [
      'Proficient in AWS, focusing on cloud infrastructure management.',
      'Developed software in C#, Angular, .NET, Node.js, and React.',
      'Innovated design patterns and maintained legacy software in a research team.',
      'Skillful architect in C#, Angular, .NET, Node.js, and React, specializing in software design and development.',
    ],
  },
  {
    company: 'Verisk',
    companySlogan: 'Decision support for insurance & finances',
    project: 'Iso',
    projectUrl: 'https://www.verisk.com/insurance/brands/iso/',
    position: 'Software Engineer',
    timeline: 'Aug 2021 - Aug 2022',
    workDescription: [
      'Constructed full-stack software: .NET MVC, Angular, React, and Node.js.',
      'Gained AWS experience in cloud infrastructure and deployment.',
      'Collaborated in Agile methodologies at a multinational company.',
      'Enhanced communication and leadership via mentoring trainees.',
    ],
  },
  {
    company: 'Crossover',
    companySlogan: 'Ultimate solutions to maintain hospitality',
    project: 'Pms',
    projectUrl: 'http://sales.crossoverpms.com/',
    position: 'Software Engineer',
    timeline: 'Dec 2019 - Aug 2021',
    workDescription: [
      'Started as Intern Software Developer, learned diverse programming.',
      'Promoted to Engineer, led Full-Stack projects for top Nepalese hotels.',
      'Mastered development phases, demonstrating expertise in software engineering.',
      'Progressed from intern to engineer, showcasing leadership in full-stack projects.',
    ],
  },
];
