import { ShowcaseSection } from '../models/showcase';

export const SHOWCASE_SECTION: ShowcaseSection[] = [
  {
    id: 1,
    name: 'Web applications',
    showCases: [
      {
        id: 1,
        isPrivate: true,
        companyName: 'Crossover Nepal',
        image: '../../../../assets/images/crossoverpms.jpg',
        title: 'Crossover Hotel & Resort Management Software',
        subtitle_one: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        subtitle_two: `
        Crossover HMS is one of the best for keeping track of guest room booking, reservations, POS services, banquet services, inventory management, accounting, and bill processing, which will help the hotel to function in an effective manner, personalizing the guest experience, and on the whole, ensuring that the guest has a wonderful stay.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling for groups and individuals, guest check-ins and room transfers, guest folio management, and a wide range of guest services like extra beds and complaints tracking. It also includes detailed reporting on guest arrivals, departures, room allocations, and occupancy, providing a seamless and efficient front desk operation.',
          'The POS system supports multiple outlets, such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, and order processing with various billing methods. The system also provides detailed sales reports, KOT and BOT reports, and revenue segregation to enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management, handling hall bookings, seat arrangements, F&B menu management, and bill settlements for events like weddings, meetings, and parties. It includes comprehensive reporting on daily collections, bookings, hall availability, and running events, ensuring smooth event operations.',
          'The housekeeping and laundry modules ensure up-to-date room status, inventory transactions, and seamless coordination with laundry services. This ensures timely service delivery and enhances the overall guest experience, including minibar management and guest billing integration.',
          'The accounts and inventory modules provide extensive financial management features, including fiscal year transactions, ledger creation, voucher management, and batch posting. The system offers detailed financial reports, such as cash flow, aging reports, trial balances, and audit logs. The inventory management system handles product management, purchase orders, inventory movement tracking, and detailed stock reports, ensuring efficient resource management and financial transparency.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://crossovernepal.com/hotel-resort-management-software.php',
        tags: '#crossover-nepal #pms',
        workDone: '.Net Core | Angular | Ant design',
        workedDate: new Date('2019/12/20'),
      },
      {
        id: 2,
        companyName: 'Crossover Nepal * BHC',
        image: '../../../../assets/images/crossoverappointment.jpg',
        title: 'BHC Patient Appointment Administration Software',
        url: 'https://khatapana.com/',
        tags: '#crossover #bhc #healthcare',
        workDone: 'Angular | .Net API | Material UI',
        workedDate: new Date('2020/07/12'),
      },
      {
        id: 3,
        companyName: 'Verisk ISO',
        image: '../../../../assets/images/veriskadmintool.jpg',
        title: 'Verisk Insurance Claims Management Admin Tool',
        url: 'https://khatapana.com/',
        tags: '#verisk #iso #insurance',
        workDone: '.Net | Angular | AWS',
        workedDate: new Date('2021/08/20'),
      },
      {
        id: 4,
        companyName: 'Verisk ISO',
        image: '../../../../assets/images/veriskinsuranceclaim.jpg',
        title: 'Verisk’s claims solutions with claims management',
        url: 'https://khatapana.com/',
        tags: '#insurance #verisk #claims',
        workDone: '.Net | Add-ins | Angular | SP',
        workedDate: new Date('2021/08/20'),
      },
      {
        id: 5,
        image: '../../../../assets/images/whitehatrasi.jpg',
        companyName: 'RASI * Whitehat',
        title: 'RASI : Restaurant Accounting that Accelerates Growth',
        url: 'https://khatapana.com/',
        tags: '#restaurant #accounting #rasi',
        workDone: '.Net | AWS | React & NodeJS',
        workedDate: new Date('2022/08/18'),
      },
      {
        id: 6,
        companyName: 'RASI * Whitehat',
        image: '../../../../assets/images/whitehatuniversal.jpg',
        title: 'RASI Universal Services for Backoffice support',
        url: 'https://khatapana.com/',
        tags: '#accounting #backoffice #universal',
        workDone: 'React | Node JS | AWS & Postgres',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 7,
        companyName: 'Resimator * IZY',
        image: '../../../../assets/images/izyportal.jpg',
        title: 'IZY Portal Simpler everyday life for every landlords',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 8,
        companyName: 'Resimator * IZY',
        image: '../../../../assets/images/izy.jpg',
        title: 'IZY Web Everything you need in one application',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 9,
        companyName: 'SoftwareQ * Senang',
        image: '../../../../assets/images/softwareqlp.jpg',
        title: 'Various websites for insurance providers linked with Senang',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 10,
        companyName: 'SoftwareQ * Senang',
        image: '../../../../assets/images/softwareqlp.jpg',
        title: 'Vehicle Portal for generation quotation for insurance',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 11,
        companyName: 'SoftwareQ * Senang',
        image: '../../../../assets/images/softwareqadminportal.jpg',
        title:
          'Admin Portal for managing overall flow and data for Vehicle Portal.',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 12,
        companyName: 'Khatapana',
        image: '../../../../assets/images/khatapana.jpg',
        title: 'Khatapana | Simplest way to manage your money!',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 13,
        companyName: 'TechNepal',
        image: '../../../../assets/images/technepal.jpg',
        title: 'Tech Nepal | Website for tech learner and enthusiast',
        url: 'https://thetechnepal.com/',
        tags: '#Personal',
        workDone: 'Full Stack (.NET, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 14,
        companyName: 'Personal Portfolio',
        image: '../../../../assets/images/kgarney.jpg',
        title: 'Kgarney | Web-app that uses firebase tools for hosting',
        url: 'https://kgarne-0.web.app/home',
        tags: '#Freelancing',
        workDone: 'Full Stack (C#, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 15,
        companyName: 'Personal Portfolio',
        image: '../../../../assets/images/generate.jpg',
        title: 'Generate | Tried to implement clone of canva functioning',
        url: 'https://gen.thetechnepal.com',
        tags: '#Personal',
        workDone: 'Full Stack (Angular, GCP)',
        workedDate: new Date('2019/07/12'),
      },
    ],
  },
  {
    id: 2,
    name: 'Mobile applications',
    showCases: [
      {
        id: 1,
        image: '../../../../assets/images/khatapana.jpg',
        title: 'Khatapana | Simplest way to manage your money!',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 2,
        image: '../../../../assets/images/technepal.jpg',
        title: 'Tech Nepal | Website for tech learner and enthusiast',
        url: 'https://thetechnepal.com/',
        tags: '#Personal',
        workDone: 'Full Stack (.NET, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 3,
        image: '../../../../assets/images/kgarney.jpg',
        title: 'Kgarney | Web-app that uses firebase tools for hosting',
        url: 'https://kgarne-0.web.app/home',
        tags: '#Freelancing',
        workDone: 'Full Stack (C#, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 4,
        image: '../../../../assets/images/generate.jpg',
        title: 'Generate | Tried to implement clone of canva functioning',
        url: 'https://gen.thetechnepal.com',
        tags: '#Personal',
        workDone: 'Full Stack (Angular, GCP)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 5,
        image: '../../../../assets/images/izy.jpg',
        title: 'IZY | Simplest way to manage your money!',
        url: 'https://izy.no/en/',
        tags: '#Resimator #Company',
        workDone: 'Full Stack(.NET, Angular)',
        workedDate: new Date('2019/07/12'),
      },
    ],
  },
  {
    id: 3,
    name: 'Graphics design',
    showCases: [
      {
        id: 1,
        image: '../../../../assets/images/foreveryng.jpg',
        title: `FOREVERYNG | Nepal's best Cosmetics website`,
        url: 'https://ananta-poudel.com.np/graphics#Foreveryng',
        tags: '#cosmetic #nepalibeauty',
        workDone: `Adobe PS,  AI,  UI/UX`,
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 2,
        image: '../../../../assets/images/khaiidim.jpg',
        title: `KHAAIDIM | Food delivery at your footstep`,
        url: 'https://ananta-poudel.com.np/graphics#Khaaidim',
        tags: '#fooddelivery #foodporn',
        workDone: 'Adobe Photoshop',
        workedDate: new Date('2019/07/12'),
      },
    ],
  },
];
