import { ShowcaseSection } from '../models/showcase';

export const SHOWCASE_SECTION: ShowcaseSection[] = [
  {
    id: 1,
    name: 'Web applications',
    showCases: [
      {
        id: 1,
        isPrivate: true,
        companyName: 'Crossover Nepal',
        bgClass: 'bg-blue-100 dark:bg-blue-950',
        image: '../../../../assets/images/crossoverpms.jpg',
        title: 'Crossover Hotel & Resort Management Software',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://crossovernepal.com/hotel-resort-management-software.php',
        tags: '#crossover-nepal #pms',
        workDone: '.Net Core | Angular | Ant design',
        workedDate: new Date('2019/12/20'),
      },
      {
        id: 2,
        companyName: 'Crossover Nepal * BHC',
        bgClass: 'bg-green-100 dark:bg-green-950',
        image: '../../../../assets/images/crossoverappointment.jpg',
        title: 'BHC Patient Appointment Administration Software',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://khatapana.com/',
        tags: '#crossover #bhc #healthcare',
        workDone: 'Angular | .Net API | Material UI',
        workedDate: new Date('2020/07/12'),
      },
      {
        id: 3,
        companyName: 'Verisk ISO',
        bgClass: 'bg-red-100 dark:bg-red-950',
        image: '../../../../assets/images/veriskadmintool.jpg',
        title: 'Verisk Insurance Claims Management Admin Tool',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://khatapana.com/',
        tags: '#verisk #iso #insurance',
        workDone: '.Net | Angular | AWS',
        workedDate: new Date('2021/08/20'),
      },
      {
        id: 4,
        companyName: 'Verisk ISO',
        bgClass: 'bg-purple-100 dark:bg-purple-950',
        image: '../../../../assets/images/veriskinsuranceclaim.jpg',
        title: 'Verisk’s claims solutions with claims management',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://khatapana.com/',
        tags: '#insurance #verisk #claims',
        workDone: '.Net | Add-ins | Angular | SP',
        workedDate: new Date('2021/08/20'),
      },
      {
        id: 5,
        image: '../../../../assets/images/whitehatrasi.jpg',
        companyName: 'RASI * Whitehat',
        bgClass: 'bg-pink-100 dark:bg-pink-950',
        title: 'RASI : Restaurant Accounting that Accelerates Growth',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://khatapana.com/',
        tags: '#restaurant #accounting #rasi',
        workDone: '.Net | AWS | React & NodeJS',
        workedDate: new Date('2022/08/18'),
      },
      {
        id: 6,
        companyName: 'RASI * Whitehat',
        image: '../../../../assets/images/whitehatuniversal.jpg',
        title: 'RASI Universal Services for Backoffice support',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://khatapana.com/',
        tags: '#accounting #backoffice #universal',
        workDone: 'React | Node JS | AWS & Postgres',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 7,
        companyName: 'Resimator * IZY',
        image: '../../../../assets/images/izyportal.jpg',
        title: 'IZY Portal Simpler everyday life for every landlords',
        subtitle: `
        Crossover Hotel Management System is the ultimate management solution to maintain hospitality and customer relationship management by a hotel.
        `,
        body: [
          'The software offers a comprehensive front office management system, including user-wise role access control, reservation handling, guest check-ins and room transfers, guest folio management, and a wide range of guest services. Detailed reporting on guest arrivals, departures, room allocations, and occupancy ensures seamless front desk operations.',
          'The POS system supports multiple outlets such as restaurants, bars, coffee shops, SPAs, and health clubs. It includes floor and table management, menu conversion, order processing, and various billing methods. Detailed sales reports, KOT/BOT reports, and revenue segregation enhance operational efficiency and profitability.',
          'The banquet management module streamlines event management with hall bookings, seat arrangements, F&B menu management, and bill settlements for events. Comprehensive reporting on daily collections, bookings, hall availability, and running events ensures smooth event operations.',
          'The housekeeping, laundry, accounts, and inventory modules ensure up-to-date room status, inventory transactions, and coordination with laundry services, enhancing guest experience. The accounts and inventory modules offer extensive financial management, including fiscal year transactions, ledger creation, voucher management, and detailed financial and stock reports for efficient resource management.',
        ],
        skills: [
          {
            name: 'Technical Skills',
            list: [
              '.NET Core',
              '.NET Framework',
              'Angular',
              'C#',
              'Material UI',
              'Ant Design',
              'JQuery',
              'HTML',
              'CSS',
              'JS',
            ],
          },
          {
            name: 'Tools and Platforms',
            list: ['Git', 'Bitbucket', 'Jira', 'LinqPad'],
          },
          {
            name: 'Methodologies',
            list: ['Agile Software Development', 'Incremental Development'],
          },
          {
            name: 'Role',
            list: ['Intern - Junior Software Engineer'],
          },
        ],
        responsibilities: [
          'Developed and maintained various modules within the Crossover HMS using .NET Core and Angular.',
          'Collaborated with cross-functional teams to integrate new features and ensure seamless user experience.',
          'Performed code reviews and provided feedback to improve code quality and maintainability.',
          'Assisted in the design and implementation of the software architecture, contributing to system scalability and performance.',
          'Participated in daily stand-ups and sprint planning meetings to ensure timely project delivery.',
          'Implemented unit tests to ensure code reliability and reduce bugs in the production environment.',
        ],
        learningOutcomes: [
          'Gained hands-on experience with .NET Core and Angular, enhancing full-stack development skills.',
          'Developed a deep understanding of hotel management systems and their functional requirements.',
          'Improved problem-solving skills by troubleshooting and debugging complex software issues.',
          'Enhanced collaboration and communication skills through regular interaction with team members and stakeholders.',
          'Learned to work efficiently in an Agile environment, participating in sprints and delivering tasks on time.',
          'Acquired knowledge in integrating third-party APIs to extend software functionalities.',
        ],
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 8,
        companyName: 'Resimator * IZY',
        image: '../../../../assets/images/izy.jpg',
        title: 'IZY Web Everything you need in one application',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 9,
        companyName: 'SoftwareQ * Senang',
        image: '../../../../assets/images/softwareqlp.jpg',
        title: 'Various websites for insurance providers linked with Senang',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 10,
        companyName: 'SoftwareQ * Senang',
        image: '../../../../assets/images/softwareqlp.jpg',
        title: 'Vehicle Portal for generation quotation for insurance',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 11,
        companyName: 'SoftwareQ * Senang',
        image: '../../../../assets/images/softwareqadminportal.jpg',
        title:
          'Admin Portal for managing overall flow and data for Vehicle Portal.',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 12,
        companyName: 'Khatapana',
        image: '../../../../assets/images/khatapana.jpg',
        title: 'Khatapana | Simplest way to manage your money!',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 13,
        companyName: 'TechNepal',
        image: '../../../../assets/images/technepal.jpg',
        title: 'Tech Nepal | Website for tech learner and enthusiast',
        url: 'https://thetechnepal.com/',
        tags: '#Personal',
        workDone: 'Full Stack (.NET, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 14,
        companyName: 'Personal Portfolio',
        image: '../../../../assets/images/kgarney.jpg',
        title: 'Kgarney | Web-app that uses firebase tools for hosting',
        url: 'https://kgarne-0.web.app/home',
        tags: '#Freelancing',
        workDone: 'Full Stack (C#, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 15,
        companyName: 'Personal Portfolio',
        image: '../../../../assets/images/generate.jpg',
        title: 'Generate | Tried to implement clone of canva functioning',
        url: 'https://gen.thetechnepal.com',
        tags: '#Personal',
        workDone: 'Full Stack (Angular, GCP)',
        workedDate: new Date('2019/07/12'),
      },
    ],
  },
  {
    id: 2,
    name: 'Mobile applications',
    showCases: [
      {
        id: 1,
        image: '../../../../assets/images/khatapana.jpg',
        title: 'Khatapana | Simplest way to manage your money!',
        url: 'https://khatapana.com/',
        tags: '#Freelancing',
        workDone: 'Frontend (Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 2,
        image: '../../../../assets/images/technepal.jpg',
        title: 'Tech Nepal | Website for tech learner and enthusiast',
        url: 'https://thetechnepal.com/',
        tags: '#Personal',
        workDone: 'Full Stack (.NET, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 3,
        image: '../../../../assets/images/kgarney.jpg',
        title: 'Kgarney | Web-app that uses firebase tools for hosting',
        url: 'https://kgarne-0.web.app/home',
        tags: '#Freelancing',
        workDone: 'Full Stack (C#, Angular)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 4,
        image: '../../../../assets/images/generate.jpg',
        title: 'Generate | Tried to implement clone of canva functioning',
        url: 'https://gen.thetechnepal.com',
        tags: '#Personal',
        workDone: 'Full Stack (Angular, GCP)',
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 5,
        image: '../../../../assets/images/izy.jpg',
        title: 'IZY | Simplest way to manage your money!',
        url: 'https://izy.no/en/',
        tags: '#Resimator #Company',
        workDone: 'Full Stack(.NET, Angular)',
        workedDate: new Date('2019/07/12'),
      },
    ],
  },
  {
    id: 3,
    name: 'Graphics design',
    showCases: [
      {
        id: 1,
        image: '../../../../assets/images/foreveryng.jpg',
        title: `FOREVERYNG | Nepal's best Cosmetics website`,
        url: 'https://ananta-poudel.com.np/graphics#Foreveryng',
        tags: '#cosmetic #nepalibeauty',
        workDone: `Adobe PS,  AI,  UI/UX`,
        workedDate: new Date('2019/07/12'),
      },
      {
        id: 2,
        image: '../../../../assets/images/khaiidim.jpg',
        title: `KHAAIDIM | Food delivery at your footstep`,
        url: 'https://ananta-poudel.com.np/graphics#Khaaidim',
        tags: '#fooddelivery #foodporn',
        workDone: 'Adobe Photoshop',
        workedDate: new Date('2019/07/12'),
      },
    ],
  },
];
